name: PHP Composer

on: # どこのbranchで実行するか
  push: # コードがmsterというブランチに追加されたときに実行
    branches: [ "master" ]
  pull_request: # master-branchに対してpull requestが要求された時にも実行
    branches: [ "master" ]

permissions: # 必要とするパーミッションの権限を指定 
  contents: read # 読み取りを指定
 
jobs: # ここで一連の作業を定義する
  build: # buildというjobの名前

    runs-on: ubuntu-latest # このjobsが実行される環境を指定

    steps: # jobs内で1つ1つ実行される作業を定義
    - uses: actions/checkout@v4 # リポジトリのコードを取得する

    - name: Validate composer.json and composer.lock # stepsの名前
      run: composer validate --strict # 実行するコマンドを指定

    - name: Cache Composer packages
      id: composer-cache # stepsに一意の値を付与
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies # 依存関係のインストール
      run: composer install --prefer-dist --no-progress # compiserをインストール
